name: Commit date to master
on:
  push:
    branches: [ master ]
 
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2
      - name: save current date
        run: |
          # Add date to file
          date > time.txt
          echo $GITHUB_SHA >> time.txt
      - name: setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
      - name: commit
        run: |
          # Stage the file, commit and push
          git add time.txt
          git commit -m "Date to keep track of version when SDK is downloaded"
          git push origin master
